### ISSUE TITLE
Moves placeholder acting a bit weird

### ISSUE THREAD

**Issue by Lorrainrm** [happyzleaf/PixelmonPlaceholders#9] opened 2018-04-01 05:30 UTC
So, im trying to parse my team poke move:
Using sneasel slot 6 as an example
%trainer_team_6_moves%
Return
Perish Song (only)
If i add a number, such as 10, it returns the move correcly:
%trainer_team_6_move_10%

(actually, im not sure if its the correct moves, they show a different list when i /movelist sneasel)

************

If i check moves from my Venusaur
%trainer_team_1_moves%
it returns a moveset of an electric pokemon, not sure which, but shows zap cannon, signal beam, etc etc.

Happens with %pokedex_3_moves% too.

using latest version, pokemon 6.3

**Comment by hqppyz** [comment] 2018-04-01 10:39
Woops, didn't mean to close this.
May have fixed it but it needs to be tested and i'm a bit busy right now.
If you want to try your luck:
https://mega.nz/#!qhYQHLQY!uex4a9Dm1yc0lRIXi7uVfR5puYjxDTrHYOtdTYWO-mk

**Comment by hqppyz** [comment] 2018-04-05 19:20
@Lorrainrm any news?

**Comment by Lorrainrm** [comment] 2018-04-05 19:23
To be honest i just saw your answear. Will test tonight

Em Qui, 5 de abr de 2018 16:21, Vincenzo Montanari <notifications@github.com>
escreveu:

**Comment by Lorrainrm** [comment] 2018-04-06 20:50
![image](https://user-images.githubusercontent.com/35673538/38443641-cc7dff02-39c2-11e8-86ba-0ebb65f6afe6.png)

![image](https://user-images.githubusercontent.com/35673538/38443651-d73b997c-39c2-11e8-84cb-1b53bce41343.png)

Comparing the %trainer_team_1_moves% and /moves venusaur

Seems more correct than before, but i see some differences.

**Comment by hqppyz** [comment] 2019-02-15 18:30
I can't reproduce, looks fine to me, feel free to open this again if it continues to give problems

**Closed as completed by hqppyz** 2019-02-15 18:30 UTC
